openapi: 3.0.1
info:
  title: AccuWeather One Active Storms Current Conditions API
  description: AccuWeather's internal product API for the One platform.
  version: v1
tags:
- name: Current Conditions
paths:
  /api/current-conditions/{locationKey}:
    get:
      tags:
      - Current Conditions
      summary: AccuWeather Retrieves the Current Conditions for a Given Location
      parameters:
      - name: locationKey
        in: path
        description: The location key to retrieve weather conditions for
        required: true
        schema:
          type: string
        example: '347628'
      - name: Locale
        in: query
        description: ISO 639-2 and ISO 3166-1 code for the locale
        schema:
          type: string
          example: en-us
        example: en-us
      - name: MeasurementDisplay
        in: query
        description: Display type for weather conditions and distance
        schema:
          $ref: '#/components/schemas/MeasurementDisplayType'
        example: Imperial
      - name: WindUnit
        in: query
        description: Additional display type for wind direction
        schema:
          $ref: '#/components/schemas/WindDirectionDisplayType'
        example: Cardinal
      - name: Theme
        in: query
        description: Theme for the application
        schema:
          $ref: '#/components/schemas/ThemeType'
        example: System
      responses:
        '200':
          description: Current Conditions found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CurrentConditions'
              examples:
                _api_current-conditions_locationKey200Example:
                  summary: Default _api_current-conditions_locationKey 200 response
                  x-microcks-default: true
                  value:
                    extended:
                      ceiling: example-value
                      cloudCover: example-value
                      dewPoint: example-value
                      gusts: example-value
                      wind: example-value
                      windValue: 12.5
                      windDegrees: 12.5
                      windDirection: example-value
                      humidity: '500123'
                      humidityValue: 1
                      indoorHumidity: '500123'
                      indoorHumidityCategory: '500123'
                      precipitation: example-value
                      pressure: example-value
                      ice: example-value
                      rain: example-value
                      snow: example-value
                      thunderstormProbability: example-value
                      uv:
                        category: example-value
                        value: 42.0
                      visibility: example-value
                      precipSummary:
                        past12Hours: example-value
                        past18Hours: example-value
                        past24Hours: example-value
                        past3Hours: example-value
                        past6Hours: example-value
                        past9Hours: example-value
                        pastHour: example-value
                    isDayTime: true
                    iconCode: 6
                    now: example-value
                    phrase: Partly cloudy
                    realFeel: example-value
                    realFeelShade: example-value
                    temperature: example-value
                    temperatureValue: 72.5
                    realFeelValue: 42.0
                    realFeelShadeValue: 42.0
                    realFeelPhrase: Partly cloudy
                    realFeelShadePhrase: Partly cloudy
                    apparentTempImperial: 72.5
                    windSpeedImperial: 12.5
        '400':
          description: Query parameter was missing or empty
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
components:
  schemas:
    MeasurementDisplayType:
      enum:
      - Metric
      - Imperial
      - Hybrid
      type: string
    CurrentConditions:
      type: object
      properties:
        extended:
          $ref: '#/components/schemas/ExtendedForecastInformation'
        isDayTime:
          type: boolean
        iconCode:
          type: integer
          format: int32
        now:
          type: string
          nullable: true
        phrase:
          type: string
          nullable: true
        realFeel:
          type: string
          nullable: true
        realFeelShade:
          type: string
          nullable: true
        temperature:
          type: string
          nullable: true
        temperatureValue:
          type: number
          format: float
          nullable: true
        realFeelValue:
          type: number
          format: float
          nullable: true
        realFeelShadeValue:
          type: number
          format: float
          nullable: true
        realFeelPhrase:
          type: string
          nullable: true
        realFeelShadePhrase:
          type: string
          nullable: true
        apparentTempImperial:
          type: number
          format: float
          nullable: true
        windSpeedImperial:
          type: number
          format: float
          nullable: true
      additionalProperties: false
    PrecipitationSummary:
      type: object
      properties:
        past12Hours:
          type: string
          nullable: true
        past18Hours:
          type: string
          nullable: true
        past24Hours:
          type: string
          nullable: true
        past3Hours:
          type: string
          nullable: true
        past6Hours:
          type: string
          nullable: true
        past9Hours:
          type: string
          nullable: true
        pastHour:
          type: string
          nullable: true
      additionalProperties: false
    UVIndex:
      type: object
      properties:
        category:
          type: string
          nullable: true
        value:
          type: number
          format: float
      additionalProperties: false
    ExtendedForecastInformation:
      type: object
      properties:
        ceiling:
          type: string
          nullable: true
        cloudCover:
          type: string
          nullable: true
        dewPoint:
          type: string
          nullable: true
        gusts:
          type: string
          nullable: true
        wind:
          type: string
          nullable: true
        windValue:
          type: number
          format: double
          nullable: true
        windDegrees:
          type: number
          format: double
          nullable: true
        windDirection:
          type: string
          nullable: true
        humidity:
          type: string
          nullable: true
        humidityValue:
          type: integer
          format: int32
          nullable: true
        indoorHumidity:
          type: string
          nullable: true
        indoorHumidityCategory:
          type: string
          nullable: true
        precipitation:
          type: string
          nullable: true
        pressure:
          type: string
          nullable: true
        ice:
          type: string
          nullable: true
        rain:
          type: string
          nullable: true
        snow:
          type: string
          nullable: true
        thunderstormProbability:
          type: string
          nullable: true
        uv:
          $ref: '#/components/schemas/UVIndex'
        visibility:
          type: string
          nullable: true
        precipSummary:
          $ref: '#/components/schemas/PrecipitationSummary'
      additionalProperties: false
    ThemeType:
      enum:
      - Light
      - Dark
      - System
      type: string
    WindDirectionDisplayType:
      enum:
      - Cardinal
      - Degrees
      type: string
