openapi: 3.2.0
info:
  title: AccuWeather One Raine API
  description: AccuWeather's internal product API for the One platform.
  version: v1
tags:
- name: Raine
paths:
  /api/raine:
    get:
      tags:
      - Raine
      summary: AccuWeather Retreives the Raine Configuration for a Page
      parameters:
      - name: Locale
        in: query
        description: ISO 639-2 and ISO 3166-1 code for the locale
        schema:
          type: string
          example: en-us
        example: en-us
      - name: MeasurementDisplay
        in: query
        description: Display type for weather conditions and distance
        schema:
          $ref: '#/components/schemas/MeasurementDisplayType'
        example: Imperial
      - name: WindUnit
        in: query
        description: Additional display type for wind direction
        schema:
          $ref: '#/components/schemas/WindDirectionDisplayType'
        example: Cardinal
      - name: Theme
        in: query
        description: Theme for the application
        schema:
          $ref: '#/components/schemas/ThemeType'
        example: System
      - name: pageGroup
        in: query
        description: The page group name.
        schema:
          type: string
        example: example-value
      - name: platform
        in: query
        description: The platform name.
        schema:
          type: string
          default: one
        example: example-value
      - name: locationKey
        in: query
        description: The location key to retrieve weather location.
        schema:
          type: string
          default: ''
        example: '347628'
      responses:
        '200':
          description: Page View response received
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RainePageView'
              examples:
                _api_raine200Example:
                  summary: Default _api_raine 200 response
                  x-microcks-default: true
                  value:
                    id: '500123'
                    test: example-value
                    platform: example-value
                    version: example-value
                    page:
                      group: example-value
                      url: https://www.accuweather.com/en/us/new-york-ny/10007/weather-forecast/347628
                      referrer: example-value
                    ads:
                      code: example-value
                      status: example-value
                      cookie3p: example-value
                    session:
                      id: '500123'
                      partner: example-value
                      utm:
                        source: AccuWeather
                        medium: example-value
                        campaign: example-value
                        term: example-value
                    user:
                      id: '500123'
                      language: example-value
                      country: example-value
                      region: example-value
                      city: example-value
                      dma: example-value
                      start: example-value
                      offset: example-value
                    network:
                      throughput: example-value
                      network: example-value
                      type: example-value
                    device:
                      name: New York
                      brand: example-value
                      version: example-value
                      category: example-value
                    weather:
                      key: '347628'
                    bot: true
                    time: example-value
        '400':
          description: Parameters are bad, details in body.
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      operationId: getApiRaine
      x-operation-id-source: derived
components:
  schemas:
    AdInfo:
      type: object
      properties:
        code:
          type:
          - string
          - 'null'
          description: 'Simplified ad code for ad slots on the page.

            Eg. ''6581/web/us/*/news_info/country_home'''
        status:
          type:
          - string
          - 'null'
          description: 'One of ''active'', ''missing'', or ''restricted'' indicating a user''s ID status

            Default missing.'
        cookie3p:
          type:
          - string
          - 'null'
          description: 'One of ''active'', ''missing'', or ''restricted'' indicating a user can access 3rd party cookies or not.

            Default missing.'
      additionalProperties: false
    SessionInfo:
      type: object
      properties:
        id:
          type:
          - string
          - 'null'
          description: Unique ID for the user's session (persistent to 10m after the last pageview)
        partner:
          type:
          - string
          - 'null'
          description: Unique ID for the partner from the URL
        utm:
          $ref: '#/components/schemas/UTMInfo'
      additionalProperties: false
    MeasurementDisplayType:
      enum:
      - Metric
      - Imperial
      - Hybrid
      type: string
    ThemeType:
      enum:
      - Light
      - Dark
      - System
      type: string
    WindDirectionDisplayType:
      enum:
      - Cardinal
      - Degrees
      type: string
    PageInfo:
      type: object
      properties:
        group:
          type:
          - string
          - 'null'
          description: Page group like 'three-day' or 'hourly' designating the page category
        url:
          type:
          - string
          - 'null'
          description: URL of the page
        referrer:
          type:
          - string
          - 'null'
          description: Referrer of the page
      additionalProperties: false
    UTMInfo:
      type: object
      properties:
        source:
          type:
          - string
          - 'null'
          description: utm_source from the URL
        medium:
          type:
          - string
          - 'null'
          description: utm_medium from the URL
        campaign:
          type:
          - string
          - 'null'
          description: utm_campaign from the URL
        term:
          type:
          - string
          - 'null'
          description: utm_term from the URL
      additionalProperties: false
    RainePageView:
      type: object
      properties:
        id:
          type:
          - string
          - 'null'
        test:
          type:
          - string
          - 'null'
        platform:
          type:
          - string
          - 'null'
        version:
          type:
          - string
          - 'null'
        page:
          $ref: '#/components/schemas/PageInfo'
        ads:
          $ref: '#/components/schemas/AdInfo'
        session:
          $ref: '#/components/schemas/SessionInfo'
        user:
          $ref: '#/components/schemas/UserInfo'
        network:
          $ref: '#/components/schemas/UserNetwork'
        device:
          $ref: '#/components/schemas/DeviceInfo'
        weather:
          $ref: '#/components/schemas/WeatherInfo'
        bot:
          type:
          - boolean
          - 'null'
          description: True if X-Akamai-Bot header is filled; default false
        time:
          type:
          - string
          - 'null'
      additionalProperties: false
    DeviceInfo:
      type: object
      properties:
        name:
          type:
          - string
          - 'null'
          description: 'Name of the user''s browser.

            Eg. ''Chrome'''
        brand:
          type:
          - string
          - 'null'
          description: 'Name of the user''s device maker.

            Eg. ''Apple'' or ''Samsung'''
        version:
          type:
          - string
          - 'null'
          description: 'Version of the user''s browser.

            Eg. ''16'''
        category:
          type:
          - string
          - 'null'
          description: One of 'mobile', 'tablet', or 'desktop'
      additionalProperties: false
    UserInfo:
      type: object
      properties:
        id:
          type:
          - string
          - 'null'
          description: Unique ID for the user (persistent across sessions)
        language:
          type:
          - string
          - 'null'
          description: Language code set for the product for the user (en-us, en-gb, etc.)
        country:
          type:
          - string
          - 'null'
          description: 'Country code for the user''s location.

            Eg. US'
        region:
          type:
          - string
          - 'null'
          description: 'Region code for the user''s location.

            Eg. PA'
        city:
          type:
          - string
          - 'null'
          description: City for the location
        dma:
          type:
          - string
          - 'null'
          description: 'DMA for the user''s location.

            Eg. 566. Not available outside of the US.'
        start:
          type:
          - string
          - 'null'
          description: 'Date of the user''s first visit.

            I.e. Cookie creation date'
        offset:
          type:
          - string
          - 'null'
          description: 'Valid string of the user''s current UTC offset in hh:mm:ss format.

            Ex. -05:00 or 05:00'
      additionalProperties: false
    WeatherInfo:
      type: object
      properties:
        key:
          type:
          - string
          - 'null'
          description: 'Surefind location key for the user''s weather location

            Eg. 335315'
      additionalProperties: false
    UserNetwork:
      type: object
      properties:
        throughput:
          type:
          - string
          - 'null'
          description: Category of 'network speed' for the user. Eg. 'vhigh'
        network:
          type:
          - string
          - 'null'
          description: Name of the network for the user. Eg. 'comcast'
        type:
          type:
          - string
          - 'null'
          description: Type of network for the user. Eg. 'cable'
      additionalProperties: false
