openapi: 3.2.0
info:
  title: AccuWeather One Hourly API
  description: AccuWeather's internal product API for the One platform.
  version: v1
tags:
- name: Hourly
paths:
  /api/hourly/{locationKey}:
    get:
      tags:
      - Hourly
      summary: AccuWeather Retrieves the Latest Hourly Forecast for a Location
      parameters:
      - name: locationKey
        in: path
        description: The location key to retrieve weather conditions for
        required: true
        schema:
          type: string
        example: '347628'
      - name: Locale
        in: query
        description: ISO 639-2 and ISO 3166-1 code for the locale
        schema:
          type: string
          example: en-us
        example: en-us
      - name: MeasurementDisplay
        in: query
        description: Display type for weather conditions and distance
        schema:
          $ref: '#/components/schemas/MeasurementDisplayType'
        example: Imperial
      - name: WindUnit
        in: query
        description: Additional display type for wind direction
        schema:
          $ref: '#/components/schemas/WindDirectionDisplayType'
        example: Cardinal
      - name: Theme
        in: query
        description: Theme for the application
        schema:
          $ref: '#/components/schemas/ThemeType'
        example: System
      - name: hourCount
        in: query
        description: The number of hour to retrieve
        schema:
          type: integer
          format: int32
          default: 24
        example: 12
      responses:
        '200':
          description: Hourly Forecast found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/HourlyForecast'
              examples:
                _api_hourly_locationKey200Example:
                  summary: Default _api_hourly_locationKey 200 response
                  x-microcks-default: true
                  value:
                  - dayOfWeek: example-value
                    shortDayOfWeek: example-value
                    fullDayOfWeek: example-value
                    epoch: 1
                    dateTime: example-value
                    displayDate: example-value
                    longDisplayDate: example-value
                    hasAlert: true
                    icon: 6
                    temperature: example-value
                    precip: example-value
                    phrase: Partly cloudy
                    realFeel: example-value
                    realFeelShade: example-value
                    isDayLight: true
                    extended:
                      ceiling: example-value
                      cloudCover: example-value
                      dewPoint: example-value
                      gusts: example-value
                      wind: example-value
                      windValue: 12.5
                      windDegrees: 12.5
                      windDirection: example-value
                      humidity: '500123'
                      humidityValue: 1
                      indoorHumidity: '500123'
                      indoorHumidityCategory: '500123'
                      precipitation: example-value
                      pressure: example-value
                      ice: example-value
                      rain: example-value
                      snow: example-value
                      thunderstormProbability: example-value
                      uv:
                        category: null
                        value: null
                      visibility: example-value
                      precipSummary:
                        past12Hours: null
                        past18Hours: null
                        past24Hours: null
                        past3Hours: null
                        past6Hours: null
                        past9Hours: null
                        pastHour: null
                    airQuality:
                      category: example-value
                      categoryColor: example-value
                      date: '2026-04-19T10:00:00Z'
                      dayOfWeek: example-value
                      dayOfWeekAbbreviated: example-value
                      displayDate: example-value
                      displayTime: example-value
                      dominantPollutant: example-value
                      hazardStatement: example-value
                      overallIndex: 42.0
                      overallPlumeLabsIndex: 42.0
                      pollutants:
                      - null
        '400':
          description: Query parameter was missing or empty
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      operationId: getApiHourlyByLocationKey
      x-operation-id-source: derived
components:
  schemas:
    MeasurementDisplayType:
      enum:
      - Metric
      - Imperial
      - Hybrid
      type: string
    ThemeType:
      enum:
      - Light
      - Dark
      - System
      type: string
    HourlyForecast:
      type: object
      properties:
        dayOfWeek:
          type:
          - string
          - 'null'
        shortDayOfWeek:
          type:
          - string
          - 'null'
        fullDayOfWeek:
          type:
          - string
          - 'null'
        epoch:
          type:
          - integer
          - 'null'
          format: int32
        dateTime:
          type:
          - string
          - 'null'
        displayDate:
          type:
          - string
          - 'null'
        longDisplayDate:
          type:
          - string
          - 'null'
        hasAlert:
          type: boolean
        icon:
          type: integer
          format: int32
        temperature:
          type:
          - string
          - 'null'
        precip:
          type:
          - string
          - 'null'
        phrase:
          type:
          - string
          - 'null'
        realFeel:
          type:
          - string
          - 'null'
        realFeelShade:
          type:
          - string
          - 'null'
        isDayLight:
          type: boolean
        extended:
          $ref: '#/components/schemas/ExtendedForecastInformation'
        airQuality:
          $ref: '#/components/schemas/AirQuality'
      additionalProperties: false
    WindDirectionDisplayType:
      enum:
      - Cardinal
      - Degrees
      type: string
    UVIndex:
      type: object
      properties:
        category:
          type:
          - string
          - 'null'
        value:
          type: number
          format: float
      additionalProperties: false
    PrecipitationSummary:
      type: object
      properties:
        past12Hours:
          type:
          - string
          - 'null'
        past18Hours:
          type:
          - string
          - 'null'
        past24Hours:
          type:
          - string
          - 'null'
        past3Hours:
          type:
          - string
          - 'null'
        past6Hours:
          type:
          - string
          - 'null'
        past9Hours:
          type:
          - string
          - 'null'
        pastHour:
          type:
          - string
          - 'null'
      additionalProperties: false
    Pollutant:
      type: object
      properties:
        concentration:
          type:
          - string
          - 'null'
        index:
          type: number
          format: double
        name:
          type:
          - string
          - 'null'
        source:
          type:
          - string
          - 'null'
        type:
          type:
          - string
          - 'null'
      additionalProperties: false
    ExtendedForecastInformation:
      type: object
      properties:
        ceiling:
          type:
          - string
          - 'null'
        cloudCover:
          type:
          - string
          - 'null'
        dewPoint:
          type:
          - string
          - 'null'
        gusts:
          type:
          - string
          - 'null'
        wind:
          type:
          - string
          - 'null'
        windValue:
          type:
          - number
          - 'null'
          format: double
        windDegrees:
          type:
          - number
          - 'null'
          format: double
        windDirection:
          type:
          - string
          - 'null'
        humidity:
          type:
          - string
          - 'null'
        humidityValue:
          type:
          - integer
          - 'null'
          format: int32
        indoorHumidity:
          type:
          - string
          - 'null'
        indoorHumidityCategory:
          type:
          - string
          - 'null'
        precipitation:
          type:
          - string
          - 'null'
        pressure:
          type:
          - string
          - 'null'
        ice:
          type:
          - string
          - 'null'
        rain:
          type:
          - string
          - 'null'
        snow:
          type:
          - string
          - 'null'
        thunderstormProbability:
          type:
          - string
          - 'null'
        uv:
          $ref: '#/components/schemas/UVIndex'
        visibility:
          type:
          - string
          - 'null'
        precipSummary:
          $ref: '#/components/schemas/PrecipitationSummary'
      additionalProperties: false
    AirQuality:
      type: object
      properties:
        category:
          type:
          - string
          - 'null'
        categoryColor:
          type:
          - string
          - 'null'
        date:
          type:
          - string
          - 'null'
          format: date-time
        dayOfWeek:
          type:
          - string
          - 'null'
        dayOfWeekAbbreviated:
          type:
          - string
          - 'null'
        displayDate:
          type:
          - string
          - 'null'
        displayTime:
          type:
          - string
          - 'null'
        dominantPollutant:
          type:
          - string
          - 'null'
        hazardStatement:
          type:
          - string
          - 'null'
        overallIndex:
          type: number
          format: double
        overallPlumeLabsIndex:
          type: number
          format: double
        pollutants:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/Pollutant'
      additionalProperties: false
