openapi: 3.2.0
info:
  title: AccuWeather One Ads API
  description: AccuWeather's internal product API for the One platform.
  version: v1
tags:
- name: Ads
paths:
  /api/ads/{locationKey}:
    get:
      tags:
      - Ads
      summary: AccuWeather Get the Data for Given Ad Slots
      parameters:
      - name: locationKey
        in: path
        description: AccuWeather location key
        required: true
        schema:
          type: string
        example: '347628'
      - name: page
        in: query
        description: Page id
        schema:
          type: string
        example: example-value
      - name: slots
        in: query
        description: Comma seperated list of ad slots
        schema:
          type: string
        example: example-value
      responses:
        '200':
          description: Ad data success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdData'
              examples:
                _api_ads_locationKey200Example:
                  summary: Default _api_ads_locationKey 200 response
                  x-microcks-default: true
                  value:
                    globalAdConfig:
                      prebidTimeout: 1
                      awxTimeout: 1
                      bundleUrl: https://www.accuweather.com/en/us/new-york-ny/10007/weather-forecast/347628
                      bundleId: '500123'
                      gptEnableSingleRequest: true
                      gptLazyLoading: example-value
                      buyItNowSkipGoogleAdManager: true
                      testVariant: example-value
                      deviceClass: example-value
                      disableInitialAdLoad: true
                      javascriptHead: example-value
                      javascriptBody: example-value
                    ortbConfig:
                      name: New York
                      domain: example-value
                      categories:
                      - example-value
                      sectionCategories:
                      - example-value
                      pageCategories:
                      - example-value
                      keywords: '347628'
                      pageUrl: https://www.accuweather.com/en/us/new-york-ny/10007/weather-forecast/347628
                      referrerUrl: https://www.accuweather.com/en/us/new-york-ny/10007/weather-forecast/347628
                      isOptimizedForMobile: true
                      hasPrivacyPolicy: true
                      publisher:
                        name: New York
                        domain: example-value
                        categories:
                        - null
                      content:
                        title: example-value
                        url: https://www.accuweather.com/en/us/new-york-ny/10007/weather-forecast/347628
                        categories:
                        - null
                        productQuality: example-value
                        context: Partly cloudy
                        keywords: '347628'
                        sourceRelationship: Indirect
                        language: example-value
                        data:
                          name: null
                          extensions: null
                          segments: null
                    adPageInfo: {}
                    adSlots: {}
                    adInfo: {}
                    uspString: example-value
                    ppid: '500123'
                    isPrebidDisabled: true
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      operationId: getApiAdsByLocationKey
      x-operation-id-source: derived
components:
  schemas:
    Ad:
      type: object
      properties:
        slot:
          type:
          - string
          - 'null'
        adDivId:
          type:
          - string
          - 'null'
        adUnitCode:
          type:
          - string
          - 'null'
        bidders:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/Bid'
        upr:
          type:
          - number
          - 'null'
          format: float
      additionalProperties: false
    OrtbSite:
      type: object
      properties:
        name:
          type:
          - string
          - 'null'
        domain:
          type:
          - string
          - 'null'
        categories:
          type:
          - array
          - 'null'
          items:
            type: string
        sectionCategories:
          type:
          - array
          - 'null'
          items:
            type: string
        pageCategories:
          type:
          - array
          - 'null'
          items:
            type: string
        keywords:
          type:
          - string
          - 'null'
        pageUrl:
          type:
          - string
          - 'null'
        referrerUrl:
          type:
          - string
          - 'null'
        isOptimizedForMobile:
          type: boolean
        hasPrivacyPolicy:
          type: boolean
        publisher:
          $ref: '#/components/schemas/OrtbPublisher'
        content:
          $ref: '#/components/schemas/OrtbContent'
      additionalProperties: false
    OrtbContent:
      type: object
      properties:
        title:
          type:
          - string
          - 'null'
        url:
          type:
          - string
          - 'null'
        categories:
          type:
          - array
          - 'null'
          items:
            type: string
        productQuality:
          type:
          - string
          - 'null'
        context:
          type:
          - string
          - 'null'
        keywords:
          type:
          - string
          - 'null'
        sourceRelationship:
          $ref: '#/components/schemas/OrtbRelationshipType'
        language:
          type:
          - string
          - 'null'
        data:
          $ref: '#/components/schemas/OrtbData'
      additionalProperties: false
    OrtbPublisher:
      type: object
      properties:
        name:
          type:
          - string
          - 'null'
        domain:
          type:
          - string
          - 'null'
        categories:
          type:
          - array
          - 'null'
          items:
            type: string
      additionalProperties: false
    AdPageInfo:
      type: object
      additionalProperties: false
    Bid:
      type: object
      properties:
        bidder:
          type:
          - string
          - 'null'
        params:
          type:
          - object
          - 'null'
          additionalProperties: {}
        isBuyItNow:
          type: boolean
      additionalProperties: false
    OrtbSegment:
      type: object
      properties:
        name:
          type:
          - string
          - 'null'
        value:
          type:
          - string
          - 'null'
      additionalProperties: false
    PrebidTimeoutOutVars:
      type: object
      properties:
        prebidTimeout:
          type: integer
          format: int32
        awxTimeout:
          type: integer
          format: int32
        bundleUrl:
          type:
          - string
          - 'null'
          deprecated: true
        bundleId:
          type:
          - string
          - 'null'
        gptEnableSingleRequest:
          type: boolean
        gptLazyLoading:
          type:
          - string
          - 'null'
        buyItNowSkipGoogleAdManager:
          type: boolean
        testVariant:
          type:
          - string
          - 'null'
        deviceClass:
          type:
          - string
          - 'null'
        disableInitialAdLoad:
          type: boolean
        javascriptHead:
          type:
          - string
          - 'null'
        javascriptBody:
          type:
          - string
          - 'null'
      additionalProperties: false
    OrtbData:
      type: object
      properties:
        name:
          type:
          - string
          - 'null'
        extensions:
          type:
          - object
          - 'null'
          additionalProperties: {}
        segments:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/OrtbSegment'
      additionalProperties: false
    OrtbRelationshipType:
      enum:
      - Indirect
      - Direct
      type: string
    AdData:
      type: object
      properties:
        globalAdConfig:
          $ref: '#/components/schemas/PrebidTimeoutOutVars'
        ortbConfig:
          $ref: '#/components/schemas/OrtbSite'
        adPageInfo:
          $ref: '#/components/schemas/AdPageInfo'
        adSlots:
          type:
          - object
          - 'null'
          additionalProperties:
            $ref: '#/components/schemas/Ad'
        adInfo:
          type:
          - object
          - 'null'
          additionalProperties:
            type: string
        uspString:
          type:
          - string
          - 'null'
        ppid:
          type:
          - string
          - 'null'
        isPrebidDisabled:
          type: boolean
      additionalProperties: false
