openapi: 3.2.0
info:
  title: AccuWeather One Test API
  description: AccuWeather's internal product API for the One platform.
  version: v1
tags:
- name: Test
paths:
  /api/test/linked-scope:
    get:
      tags:
      - Test
      summary: AccuWeather Example of a Simple Scope and Linked Scope
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RecentLocation'
              examples:
                _api_test_linked-scope200Example:
                  summary: Default _api_test_linked-scope 200 response
                  x-microcks-default: true
                  value:
                    id: '500123'
                    key: '347628'
                    name: New York
                    longName: New York
                    displayName: New York
                    localTime: example-value
                    displayTemperature: example-value
                    icon: 6
                    color: example-value
                    isBefore7PM: true
                    isDayTime: true
                    latitude: 40.7128
                    longitude: -74.006
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      operationId: getApiTestLinkedScope
      x-operation-id-source: derived
components:
  schemas:
    RecentLocation:
      type: object
      properties:
        id:
          type:
          - string
          - 'null'
        key:
          type:
          - string
          - 'null'
        name:
          type:
          - string
          - 'null'
        longName:
          type:
          - string
          - 'null'
        displayName:
          type:
          - string
          - 'null'
        localTime:
          type:
          - string
          - 'null'
        displayTemperature:
          type:
          - string
          - 'null'
        icon:
          type:
          - integer
          - 'null'
          format: int32
        color:
          type:
          - string
          - 'null'
        isBefore7PM:
          type: boolean
        isDayTime:
          type: boolean
        latitude:
          type:
          - number
          - 'null'
          format: double
        longitude:
          type:
          - number
          - 'null'
          format: double
      additionalProperties: false
