openapi: 3.2.0
info:
  title: AccuWeather One Storm API
  description: AccuWeather's internal product API for the One platform.
  version: v1
tags:
- name: Storm
paths:
  /api/storm/{year}/{basinId}/{depressionNumber}:
    get:
      tags:
      - Storm
      summary: AccuWeather Retrieves Data About a Specific Storm
      parameters:
      - name: year
        in: path
        description: The year of the storm.
        required: true
        schema:
          type: integer
          format: int32
        example: 1
      - name: basinId
        in: path
        description: The id of the basin for the storm.
        required: true
        schema:
          type: string
        example: '500123'
      - name: depressionNumber
        in: path
        description: The the number given to the storm.
        required: true
        schema:
          type: integer
          format: int32
        example: 1
      - name: includePositions
        in: query
        description: A flag for whether to get all of the storms positions
        schema:
          type: boolean
        example: true
      - name: Locale
        in: query
        description: ISO 639-2 and ISO 3166-1 code for the locale
        schema:
          type: string
          example: en-us
        example: en-us
      - name: MeasurementDisplay
        in: query
        description: Display type for weather conditions and distance
        schema:
          $ref: '#/components/schemas/MeasurementDisplayType'
        example: Imperial
      - name: WindUnit
        in: query
        description: Additional display type for wind direction
        schema:
          $ref: '#/components/schemas/WindDirectionDisplayType'
        example: Cardinal
      - name: Theme
        in: query
        description: Theme for the application
        schema:
          $ref: '#/components/schemas/ThemeType'
        example: System
      - name: locationKey
        in: query
        description: The location key to retrieve tropical conditions for
        schema:
          type: string
        example: '347628'
      responses:
        '200':
          description: Storm found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Storm'
              examples:
                _api_storm_year_basinId_depressionNumber200Example:
                  summary: Default _api_storm_year_basinId_depressionNumber 200 response
                  x-microcks-default: true
                  value:
                    accuId: 1
                    eventKey: '347628'
                    isActive: true
                    basin: example-value
                    basinId: AL
                    basinSlug: example-value
                    governmentId: 1
                    level: example-value
                    name: New York
                    updatedStormName: New York
                    stormPositions:
                    - coordinates:
                        type: null
                        coordinates: null
                      dateTime: '2026-04-19T10:00:00Z'
                      localDate: '2026-04-19T10:00:00Z'
                      localDayOfWeek: example-value
                      dateTimeLabelShort: example-value
                      dateTimeLabel: example-value
                      shortDateShortTimeLabel: example-value
                      direction: example-value
                      isCurrent: true
                      isHistorical: true
                      isMarked: true
                      isPeak: true
                      latitude: 40.7128
                      longitude: -74.006
                      maximumSustainedWind: example-value
                      maximumSustainedWindValue: 12.5
                      maximumWindGust: example-value
                      maximumWindGustValue: 12.5
                      windDegrees: 12.5
                      minimumPressure: example-value
                      position: example-value
                      speed: example-value
                      status: example-value
                      localizedStatus: example-value
                      statusName: New York
                      statusIcon: ExtratropicalStorm
                      statusIconString: '6'
                      landmarkReferences:
                      - null
                      eventKey: '347628'
                    peakPosition:
                      coordinates:
                        type: example-value
                        coordinates:
                        - null
                      dateTime: '2026-04-19T10:00:00Z'
                      localDate: '2026-04-19T10:00:00Z'
                      localDayOfWeek: example-value
                      dateTimeLabelShort: example-value
                      dateTimeLabel: example-value
                      shortDateShortTimeLabel: example-value
                      direction: example-value
                      isCurrent: true
                      isHistorical: true
                      isMarked: true
                      isPeak: true
                      latitude: 40.7128
                      longitude: -74.006
                      maximumSustainedWind: example-value
                      maximumSustainedWindValue: 12.5
                      maximumWindGust: example-value
                      maximumWindGustValue: 12.5
                      windDegrees: 12.5
                      minimumPressure: example-value
                      position: example-value
                      speed: example-value
                      status: example-value
                      localizedStatus: example-value
                      statusName: New York
                      statusIcon: ExtratropicalStorm
                      statusIconString: '6'
                      landmarkReferences:
                      - landmark: null
                        distance: null
                      eventKey: '347628'
                    start: '2026-04-19T10:00:00Z'
                    startEpoch: 1
                    end: '2026-04-19T10:00:00Z'
                    localStart: '2026-04-19T10:00:00Z'
                    localEnd: '2026-04-19T10:00:00Z'
                    year: 1
                    isFuture: true
                    stormLink: example-value
                    localizedStartDate: example-value
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      operationId: getApiStormByYearByBasinIdByDepressionNumber
      x-operation-id-source: derived
components:
  schemas:
    MeasurementDisplayType:
      enum:
      - Metric
      - Imperial
      - Hybrid
      type: string
    BasinId:
      enum:
      - AL
      - EP
      - SI
      - NI
      - CP
      - NP
      - SP
      type: string
    LandmarkReference:
      type: object
      properties:
        landmark:
          type:
          - string
          - 'null'
        distance:
          type:
          - string
          - 'null'
      additionalProperties: false
    ThemeType:
      enum:
      - Light
      - Dark
      - System
      type: string
    StormPosition:
      type: object
      properties:
        coordinates:
          $ref: '#/components/schemas/Polygon'
        dateTime:
          type:
          - string
          - 'null'
          format: date-time
        localDate:
          type:
          - string
          - 'null'
          format: date-time
        localDayOfWeek:
          type:
          - string
          - 'null'
        dateTimeLabelShort:
          type:
          - string
          - 'null'
        dateTimeLabel:
          type:
          - string
          - 'null'
        shortDateShortTimeLabel:
          type:
          - string
          - 'null'
        direction:
          type:
          - string
          - 'null'
        isCurrent:
          type:
          - boolean
          - 'null'
        isHistorical:
          type:
          - boolean
          - 'null'
        isMarked:
          type: boolean
        isPeak:
          type:
          - boolean
          - 'null'
        latitude:
          type:
          - number
          - 'null'
          format: double
        longitude:
          type:
          - number
          - 'null'
          format: double
        maximumSustainedWind:
          type:
          - string
          - 'null'
        maximumSustainedWindValue:
          type:
          - number
          - 'null'
          format: float
        maximumWindGust:
          type:
          - string
          - 'null'
        maximumWindGustValue:
          type:
          - number
          - 'null'
          format: float
        windDegrees:
          type:
          - number
          - 'null'
          format: float
        minimumPressure:
          type:
          - string
          - 'null'
        position:
          type:
          - string
          - 'null'
        speed:
          type:
          - string
          - 'null'
        status:
          type:
          - string
          - 'null'
        localizedStatus:
          type:
          - string
          - 'null'
        statusName:
          type:
          - string
          - 'null'
          readOnly: true
        statusIcon:
          $ref: '#/components/schemas/StormIcon'
        statusIconString:
          type:
          - string
          - 'null'
          readOnly: true
        landmarkReferences:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/LandmarkReference'
        eventKey:
          type:
          - string
          - 'null'
      additionalProperties: false
    Polygon:
      type: object
      properties:
        type:
          type:
          - string
          - 'null'
        coordinates:
          type:
          - array
          - 'null'
          items:
            type: array
            items:
              type: array
              items:
                type: number
                format: double
      additionalProperties: false
    StormIcon:
      enum:
      - ExtratropicalStorm
      - Subtropical
      - Category0
      - Category1
      - Category2
      - Category3
      - Category4
      - Category5
      - TropicalRainStorm
      - TropicalDepression
      type: string
    WindDirectionDisplayType:
      enum:
      - Cardinal
      - Degrees
      type: string
    Storm:
      type: object
      properties:
        accuId:
          type:
          - integer
          - 'null'
          format: int32
        eventKey:
          type:
          - string
          - 'null'
        isActive:
          type: boolean
        basin:
          type:
          - string
          - 'null'
          readOnly: true
        basinId:
          $ref: '#/components/schemas/BasinId'
        basinSlug:
          type:
          - string
          - 'null'
        governmentId:
          type:
          - integer
          - 'null'
          format: int32
        level:
          type:
          - string
          - 'null'
        name:
          type:
          - string
          - 'null'
        updatedStormName:
          type:
          - string
          - 'null'
        stormPositions:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/StormPosition'
        peakPosition:
          $ref: '#/components/schemas/StormPosition'
        start:
          type:
          - string
          - 'null'
          format: date-time
        startEpoch:
          type:
          - integer
          - 'null'
          format: int32
        end:
          type:
          - string
          - 'null'
          format: date-time
        localStart:
          type:
          - string
          - 'null'
          format: date-time
        localEnd:
          type:
          - string
          - 'null'
          format: date-time
        year:
          type: integer
          format: int32
        isFuture:
          type: boolean
        stormLink:
          type:
          - string
          - 'null'
        localizedStartDate:
          type:
          - string
          - 'null'
      additionalProperties: false
